build:
    dependencies:
        before:
            - composer global require "fxp/composer-asset-plugin:1.0.0"

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true

checks:
    php:
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        too_many_arguments: true
        simplify_boolean_return: true
        scope_indentation:
            spaces_per_level: '4'
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_braces_around_control_structures: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        prefer_unix_line_ending: true
        php5_style_constructor: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        one_class_per_file: true
        no_unnecessary_if: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_space_inside_cast_operator: true
        no_space_between_concatenation_operator: true
        no_space_before_semicolon: true
        no_space_around_object_operator: true
        no_short_open_tag: true
        no_long_variable_names:
            maximum: '30'
        no_goto: true
        no_global_keyword: true
        no_eval: true
        no_error_suppression: true
        no_empty_statements: true
        no_duplicate_arguments: true
        no_debug_code: true
        more_specific_types_in_doc_comments: true
        missing_arguments: true
        method_calls_on_non_object: true
        lowercase_php_keywords: true
        lowercase_basic_constants: true
        line_length:
            max_length: '120'
        instanceof_class_exists: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        foreach_traversable: true
        foreach_usable_as_reference: true
        fix_linefeed: true
        ensure_lower_case_builtin_functions: true
        encourage_shallow_comparison: true
        encourage_postdec_operator: true
        deadlock_detection_in_loops: true
        catch_class_exists: true
        blank_line_after_namespace_declaration: true
        avoid_usage_of_logical_operators: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_length_functions_in_loops: true
        avoid_fixme_comments: true
        avoid_duplicate_types: true
        avoid_corrupting_byteorder_marks: true
        avoid_aliased_php_functions: true
        argument_type_checks: true
        verify_argument_usable_as_reference: true
        spacing_of_function_arguments: true
        single_namespace_per_use: true
        optional_parameters_at_the_end: true
        non_commented_empty_catch_block: true
        function_body_start_on_new_line: true