build:
    dependencies:
        before:
            - sudo composer self-update && composer --version
            - composer global require "fxp/composer-asset-plugin:1.0.0"
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true

filter:
    excluded_paths:
        - tests/*
        - vendor/*